version: "3.8"

services: 
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
  api:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app:cached   # montamos la carpeta del código
      - /app/node_modules        # mantenemos node_modules dentro del contenedor

